export const fallenImages = new Map<string, string[]>()
function importAll(r: any) {
  r.keys().forEach((k: string) => {
    const name = k.split('/')[1]
    const personImages = fallenImages.get(name) || []
    personImages.push(r(k).default)
    fallenImages.set(name, personImages)
  });
}

importAll(require.context('../resources/images/fallen', true));

// loaded from google sheets in People.tsx
// used for dev, on prod live data is loaded
const data: any = [
   {
      "name": "သက်ဇော်ဦး",
      "confirmed": "",
      "date": "11/3/2021",
      "city": "မြိုင် (မ‌ကွေး)",
      "details": "မြိုင် ၁ ထန်းငယ်တောရွာ တွင် နေထိုင်သူ။ ဆီးခုံကျည်ထိ၍သေဆုံး။",
      "age": "34",
      "folder": "",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko thet zaw oo",
      "enDetails": ""
   },
   {
      "name": "တိုက်ပေါ်",
      "confirmed": "",
      "date": "11/3/2021",
      "city": "မြိုင် (မ‌ကွေး)",
      "details": "မြိုင် ၂ ဇာတိကန်ပူးကျေးရွာတွင် နေထိုင်သူ။ ဦးခေါင်းပွင့်၍သေဆုံး။",
      "age": "",
      "folder": "",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko tike paw",
      "enDetails": ""
   },
   {
      "name": "အောင်ကျော်ဆင့်",
      "confirmed": "",
      "date": "11/3/2021",
      "city": "မြိုင် (မ‌ကွေး)",
      "details": "ဝက်ကျူံး ၁ ကျေးရွာတွင် နေထိုင်သူ။ ရင်ဘတ်ကျည်ထိ၍သေဆုံး။",
      "age": "21",
      "folder": "",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko aung kyaw sint",
      "enDetails": ""
   },
   {
      "name": "ဥာဏ်၀င်း (ခ) မြိုင်၀င်း",
      "confirmed": "",
      "date": "11/3/2021",
      "city": "မြိုင် (မ‌ကွေး)",
      "details": "အမှတ်၂ ဘုရားကြီးအရှေ့ဘက် မန်းလေးလမ်းတွင် နေထိုင်သူ။",
      "age": "33",
      "folder": "",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko nyan win @ ko myaing win",
      "enDetails": ""
   },
   {
      "name": "သန်းဇော်",
      "confirmed": "",
      "date": "11/3/2021",
      "city": "မြိုင် (မ‌ကွေး)",
      "details": "သန်မြေကျင်းရွာတွင် နေထိုင်သူ။",
      "age": "",
      "folder": "",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko than zaw",
      "enDetails": ""
   },
   {
      "name": "ကြည်ဖြိုးဝေ",
      "confirmed": "",
      "date": "11/3/2021",
      "city": "မြိုင် (မ‌ကွေး)",
      "details": "ကြက်မောက်ရွာတွင် နေထိုင်သူ။",
      "age": "18",
      "folder": "",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko kyi phyoe wai",
      "enDetails": ""
   },
   {
      "name": "သိုက်စိုး",
      "confirmed": "",
      "date": "11/3/2021",
      "city": "မြိုင် (မ‌ကွေး)",
      "details": "ဘောဓုံကျေးရွာတွင် နေထိုင်သူ။ ",
      "age": "",
      "folder": "",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko thike soe",
      "enDetails": ""
   },
   {
      "name": "ဝင်းနိုင်",
      "confirmed": "",
      "date": "11/3/2021",
      "city": "ထားဝယ်",
      "details": "အရန်မီးသတ်တပ်ဖွဲ့ဝင်။  ကြက်စာပြင်ရပ်ကွက်အတွင်း ဖမ်းဆီးခံရသူများနှင့်ကျဆုံးာရဲဘော်များဆုတောင်းပွဲလုပ်စဉ် အာဏာသိမ်းစစ်တပ်က သေနတ်ပစ်ဖြိုခွင်းမှုကြောင့် သေဆုံးခဲ့။ https://bit.ly/3cijgUC",
      "age": "",
      "folder": "win naing",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u win naing",
      "enDetails": ""
   },
   {
      "name": "လင်းထက်",
      "confirmed": "TRUE",
      "date": "11/3/2021",
      "city": "မန္တလေး",
      "details": "ရတနာပုံတက္ကသိုလ် ဘူမိဗေဒ ဒုတိယနှစ်ကျောင်းသား။ လမ်း ၉၀၊ ၃၀ နှင့် ၃၁ လမ်း၊ ကိုးလုံးတကာဘုရား အနီး မြတောင်သပိတ်ကို ၁၀နာရီခွဲဝန်းကျင်တွင် ဖြိုခွင်းရာ ကျည်အစစ်မှန်၍ သေဆုံး။ ရုပ်အလောင်းကို စစ်တပ်က ကောက်ယူသွား။ https://bit.ly/30w040f https://bit.ly/3tndoAz",
      "age": "19",
      "folder": "lin htet",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg lin htet",
      "enDetails": ""
   },
   {
      "name": "ဇော်အောင်လေး (ခ) ရွှေအ",
      "confirmed": "TRUE",
      "date": "11/3/2021",
      "city": "ပဲခူး",
      "details": "ရွှေသာလျောင်းလမ်း၊ ရေကျော်နေ။ ဦးမြင့်လွင်၊ ဒေါ်ခင်မိုး၏သား။ မွေးရာပါအကြားအာရုံမသန်စွမ်းနဲ့စကားမပြောနိုင်ဘဲ အနှိပ်သည်အဖြစ် အသက်မွေး။ ပဲခူးမြို့ မဇင်းတစ်လမ်းထိပ်တွင် ဆန္ဒပြတာကို ရပ်ကြည့်ရာမှ ဦးခေါင်းကျည်မှန်။ https://bit.ly/3vhlvAq https://bit.ly/3bxxp14 https://bit.ly/3cfV8ly (v)https://bit.ly/2N8N79z",
      "age": "33",
      "folder": "shwe a",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko zaw lay @ ko shwe ah",
      "enDetails": ""
   },
   {
      "name": "‌ထူးအောင်ကျော်",
      "confirmed": "TRUE",
      "date": "11/3/2021",
      "city": "မြင်းခြံ",
      "details": "မတ်လ ၁၀ရက်နေ့ က မြင်းခြံ ဆန္ဒပြလူထုသပိတ် ပစ်ခတ်ဖြိုခွဲခံရမှုမှာ မျက်လုံးကျည်ထိမှန်ခဲ့။ မတ်လ ၁၁ရက်နေ့မှာ သေဆုံး။",
      "age": "",
      "folder": "htoo aung kyaw",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko htoo aung kyaw",
      "enDetails": ""
   },
   {
      "name": "ချစ်မင်းသူ",
      "confirmed": "TRUE",
      "date": "11/3/2021",
      "city": "ရန်ကုန်",
      "details": "\"မိန်းမရယ် ငါ့ကို ခွင့်လွှတ်ပါ။ ဒီ​နေ့ ငါမထွက်လို့ ငါလိုလူ​တွေများရင် ဒီနိုင်ငံကြီး ဒီမိုက​ရေစီမရ​တော့ဘူး\" ဟု အိမ်က မထွက်ခင် ပြောသွား။ ရန်ကုန်ဒဂုံမြောက်ပိုင်း ၃၅ ထိပ် ဗိုလ်မင်း​ရောင်လမ်းမ​ပေါ်မှ စစ်အာဏာရှင်ဆန့်ကျင်​ရေးသပိတ်ကို စစ်တပ်နှင့်ရဲက ကျည်အစစ်ဖြင့်ပစ်ခတ်ဖြိုခွင်းခံရ။ သပိတ်​ရှေ့တန်းမှ ဒိုင်းကာသူဖြစ်ပြီး ချိန်ပစ်သော​ကြောင့် ဒိုင်းကို ​ဖောက်ကာ နားထင်ထိမှန်သေဆုံး။ ကိုယ်ဝန် ၂လရှိအမျိုးသမီး နှင့် ကလေး တစ်ဦးကျန်ရစ်ခဲ့၊ ၄၉ ရပ်ကွက်နေ  https://bit.ly/2N8GP9X https://bit.ly/3clIqSm (v)https://bit.ly/2OJVuIS (v)https://bit.ly/2PLad6W",
      "age": "25",
      "folder": "chit min thu",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko chit min thu",
      "enDetails": ""
   },
   {
      "name": "အောင်ဆန်းဦး (ခ) ချစ်စမ်းအောင်",
      "confirmed": "TRUE",
      "date": "11/3/2021",
      "city": "မုံရွာ",
      "details": "နန္ဒဝန်ရပ်ကွက်တွင် နေထိုင်သူ။ မတ်လ ၃ရက်က မုံရွာ ပြည်ထောင်စုလမ်း ဘုရားနီအနီး ဖြိုခွင်းမှုတွင် ကျည်ထိမှန်ခဲ့ပြီး လက်မောင်ရင်းပေါက်ထွက်၊နံရိုးကျိုးကာ အဆုတ်ကိုလည်း ထိခိုက်ခဲ့။ ထိုနေ့တွင် မန္တလေးဆေးရုံကြီးသို့ အရေးပေါ် ပို့ဆောင်ခဲ့။ မနက် ၆ နာရီ ၄၅ တွင် ဆုံးပါး။ https://bit.ly/2OFxvLd",
      "age": "38",
      "folder": "",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u aung san oo @ u chit san aung",
      "enDetails": ""
   },
   {
      "name": "ဇော်မြတ်လင်း",
      "confirmed": "TRUE",
      "date": "9/3/2021",
      "city": "ရန်ကုန်",
      "details": "စု အသက်မွေးဝမ်းကျောင်းသိပ္ပံ - ရွှေပြည်သာ တာဝန်ခံ။ မတ် လ ၈ ရက်နေ့တွင် မတရား ဖမ်းဆီးခေါ်ဆောင်သွားပြီးနောက် ကွယ်လွန်ခဲ့။ ဇနီးနှင့် ၁၀နှစ်အရွယ် သားလေးတစ်ယောက် ကျန်ရစ်။ bit.ly/3l0Wt3F bit.ly/30vaooY https://bit.ly/3rxBZSC https://bit.ly/3bvcNqk",
      "age": "46",
      "folder": "zaw myat lin",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u zaw myat lin",
      "enDetails": ""
   },
   {
      "name": "ကိုကိုလေး (ခ) ချိုတား (ခ) မုဟမ္မဒ် အမီနွလ္လာဟ်",
      "confirmed": "TRUE",
      "date": "8/3/2021",
      "city": "မြစ်ကြီးနား",
      "details": "မူလတန်း ကျောင်းဆရာ။ ကျွန်းပင်သာ၊ရပ်ကွက်သား။ မြစ်ကြီးနား သပိတ်ဖြိုခွဲချိန်တွင် ခေါင်းကိုကျည်ထိပြီးသေဆုံး။ ည​နေ ၅နာရီတွင်ပို့ဆောင်သဂြိုလ်(ဒါဖွာနာ) ပြုလုပ်။ https://bit.ly/2O3BNw1 https://bit.ly/3ejG8pi",
      "age": "62",
      "folder": "ko ko lay",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u ko ko lay @ u cho tharr",
      "enDetails": ""
   },
   {
      "name": "ဇင်မင်းထက်",
      "confirmed": "TRUE",
      "date": "8/3/2021",
      "city": "မြစ်ကြီးနား",
      "details": "ကချင်စု တွင်နေထိုင်။ ပန်းတိမ်ဆိုင်မှာ အလုပ်လုပ်ပြီး  မိခင်ကို  အလုပ်အကျွေးပြုနေသူ။ ဆန္ဒပြပြည်သူများကို ရဲ၊ စစ်သားများက ပစ်ခတ်ဖြိုခွင်ချိန်တွင် သပိတ်ပြည်သူများကို ဒိုင်းကာ ကာကွယ်​ရင်း ဦးခေါင်းတွင် ကျည်ဆံထိမှန်ကာ သေဆုံး။ မောင်နှမသုံးယောက်ထဲမှ အငယ်ဆုံး။ https://bit.ly/3bqnZo5 https://bit.ly/38l4dbt https://bit.ly/3evVOpR (v) https://bit.ly/2OvjkZ5",
      "age": "23",
      "folder": "zin min htet",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko zin min htet",
      "enDetails": ""
   },
   {
      "name": "သီဟဦး",
      "confirmed": "TRUE",
      "date": "8/3/2021",
      "city": "ဖျာပုံ",
      "details": "အမှတ်(၁၅)ရပ်ကွက်၊ အောင်သပြေ(၄) လမ်းတွင်နေထိုင်။ ဖျာပုံသပိတ်စစ်ကြောင်း ဖြိုခွဲပြီး ဖမ်းဆီးမှုလုပ်ခဲသဖြင့် ဒေသခံများက ပြန်လွှတ်ပေးဖို့ တောင်းဆိုခဲ့။ ပစ်ခတ်ခဲ့၍ ဝမ်းဗိုက်ကျည်ဆန်ထိမှန်ပြီး ကျဆုံး။ ဇနီးနှင့် ၆အရွယ်သမီးတစ်ဦး၊ ၁နှစ်အရွယ်သားတစ်ဦးတို့ ကျန်ရစ်ခဲ့။ https://bit.ly/3rxJkSg",
      "age": "30",
      "folder": "thiha oo",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko thiha oo",
      "enDetails": ""
   },
   {
      "name": "အောင်မြတ်လင်း",
      "confirmed": "TRUE",
      "date": "7/3/2021",
      "city": "ထီးလင်း (မကွေး)",
      "details": "ထီးလင်းမြို့မှ သုံးမိုင်အကွာ (ဆိုင်ကယ်ဖြင့် ၁၀ မိနစ်ခန့်) အကွာအဝေးရှိ ထန်းပင်ကုန်းရွာသား။ ည ၈နာရီခန့်တွင် လူသိများသည့် လူငယ်တစ်ဦးကို ရဲက ဖမ်းဆီးသွားရာမှ မြို့ခံများက ပြန်လွှတ်ပေးရန်တောင်းဆို။ ည၁၀နာရီဝန်းကျင် ရဲစခန်းရှေ့ တောင်းဆိုလူအုပ်ကို ရဲက ပစ်ခတ်လူစုခွဲရာ သေနတ်ကျည် ဒဏ်ရာနဲ့ ပွဲချင်းပြီး သေဆုံးခဲ့။ https://bit.ly/3uY0Y3D https://bit.ly/3kWmmkV",
      "age": "23",
      "folder": "aung myat lin",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko aung myat lin",
      "enDetails": ""
   },
   {
      "name": "သိန်းလွင်",
      "confirmed": "TRUE",
      "date": "7/3/2021",
      "city": "မူဆယ်",
      "details": "မူဆယ်မြို့ ဟိုမွန်ရပ်ကွက်နေထိုင်သူ။ ဖေဖော်ဝါရီလ ၂၈ရက်နေ့ က မူဆယ်မြို့ မန်ဝိတ်းဂိတ်ပေါက်ဆန္ဒထုတ်ဖော် ရာတွင်ပူးပေါင်းပါဝင်ခဲ့။ ဆန္ဒထုတ်ဖော်နေစဥ်အတွင်း လက်နက်ပါလာပြီး၊အော်ဟစ်မှုများရှိ၍ ရဲတပ်ဖွဲ့မှခေါ်သွား။ မည်သည့်ဒဏ်ရာမှမရှိဘဲ အကောင်းပကတိအတိုင်းခေါ်သွား။ သေဆုံးသူ၏ မျက်နှာနှင့်ဦးခေါင်း၊ခန္ဓာကိုယ်တွင်ဒဏ်ရာ အများအပြားတွေ့ရ။ https://bit.ly/3rq9uGs",
      "age": "43",
      "folder": "",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u thein lwin",
      "enDetails": ""
   },
   {
      "name": "ခင်မောင်လတ် (ခ) ရှဟီဒီမုဟမ္မဒ်ရိုရှန်",
      "confirmed": "TRUE",
      "date": "7/3/2021",
      "city": "ရန်ကုန်",
      "details": "NLD ၇ရပ်ကွက် ဥက္ကဌ။ ပန်းဘဲတန်းမြို့နယ် လမ်း ၃၀ အလယ်ဘလောက်ကို စစ်တပ်လက်နက်ကိုင်များ ဝင်ရောက်စီးနင်း ဖမ်းဆီးခံရ။  ညတွင်းချင်းဆုံးသွား bit.ly/3sX9Vs1",
      "age": "58",
      "folder": "khin maung lat",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u khin maung latt",
      "enDetails": ""
   },
   {
      "name": "ဝေယံမောင်မောင် (ခ) မန်ဆွမ်းခိုင်",
      "confirmed": "TRUE",
      "date": "6/3/2021",
      "city": "ရန်ကုန်",
      "details": "နွေဦးတော်လှန်ရေးအတွက် မတ်လ ၃ရက်နေ့တွင် မြောက်ဥက္ကလာပအဝိုင်းတွင် ပေါင်သေနတ်ထိမှန်ခဲ့၍ ဖမ်းဆီးခံရ။ မြောက်ဥက္ကလာပဆေးရုံမှာ ပိုင်ရှင်မဲ့အလောင်းအဖြစ်တွေ့ရှိ။ https://bit.ly/3sXN3sp",
      "age": "27",
      "folder": "wai yan maung maung",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko wai yan maung maung @ man swoon khine",
      "enDetails": ""
   },
   {
      "name": "နန်းဝေ",
      "confirmed": "TRUE",
      "date": "5/3/2021",
      "city": "မကွေး",
      "details": "ကျောင်းကုန်းကြီးရွာ၊ ပွင့်ဖြူမြို့နယ်တွင် ပြည်ခိုင်ဖြိုးအားပေးသူများမှ ဓားဖြင့် ဝိုင်းခုတ် bit.ly/3rnb23Z bit.ly/3egyz2z",
      "age": "17",
      "folder": "nan wai",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg nan wai",
      "enDetails": ""
   },
   {
      "name": "ထွေးနိုင်",
      "confirmed": "TRUE",
      "date": "5/3/2021",
      "city": "မကွေး",
      "details": "ကျောင်းကုန်းကြီးရွာ၊ ပွင့်ဖြူမြို့နယ်တွင် ပြည်ခိုင်ဖြိုးအားပေးသူများမှ ဓားဖြင့် ဝိုင်းခုတ် bit.ly/3rnb23Z bit.ly/3egyz2z",
      "age": "53",
      "folder": "htwe naing",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u htwe naing",
      "enDetails": ""
   },
   {
      "name": "နိုင်မင်းကို",
      "confirmed": "TRUE",
      "date": "5/3/2021",
      "city": "မန္တလေး",
      "details": "၄၃ နှင့် ၈၈ လမ်း မိုးကောင်းဓမ္မာရုံး အရှေ့ပတ္တာ စိန်ပန်းနေသူ။ မတ်လ ၅ ရက်နေ့တွင် မြတောင်စစ်ကြောင်းမှာ အားလုံးထွက်ပြေးနိုင်ရန် သစ်တုံးများဖြင့်လမ်းပိတ်ပေးရင်းခြေထောက်အပစ်ခံရပြီး အဖမ်းခံရ။ ရိုက်နှက်နှိပ်စက်သော ဒဏ်ရာများဖြင့် ကွယ်လွန်။ bit.ly/3bqELU9 bit.ly/2Pwjcsz",
      "age": "21",
      "folder": "naing min ko",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko naing min ko",
      "enDetails": ""
   },
   {
      "name": "ဇော်မျိုး",
      "confirmed": "TRUE",
      "date": "5/3/2021",
      "city": "မန္တလေး",
      "details": "၄၉ လမ်း၊ ၁၁၁ လမ်းအနီးတွင် လည်ပင်းကျည်မှန် သေဆုံးခဲ့။ ကိုယ်၀န်နှင့်ဇနီးသည်နှင့် ၅နှစ်အရွယ် သားတစ်ယောက်ကျန်ရစ်။ https://bit.ly/2OA1WSF bit.ly/2OoXTIY https://bit.ly/3qoyFI8",
      "age": "27",
      "folder": "zaw myo",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko zaw myo",
      "enDetails": ""
   },
   {
      "name": "ခွန်မောင်ဖြူ",
      "confirmed": "TRUE",
      "date": "4/3/2021",
      "city": "ပင်လောင်း (ရှမ်းပြည်)",
      "details": "ပင်လောင်းမြို့နယ်ကော်မရှင် အဖွဲ့ခွဲဥက္ကဌ။ ရွေးကောက်ပွဲကော်မရှင်အဖွဲ့ဝင်တွေဖမ်းဆီးခံထားရသူတစ်ဦး။ အဖမ်းခံထားရစဉ် ရောဂါအခံတွေ ပြန်ထလာကာ စစ်ဆေးရုံကို ပို့ဆောင်ကုသပြီးဆုံးပါး။ https://bit.ly/2PJSehm",
      "age": "",
      "folder": "",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "kwon maung phyu",
      "enDetails": ""
   },
   {
      "name": "ထွန်းမောင်",
      "confirmed": "TRUE",
      "date": "4/3/2021",
      "city": "ရန်ကုန်",
      "details": "မြောက်ဥက္ကလာပဖြိုခွင်းမှုတွင် ခေါင်းတစ်ချက် ပေါင်တစ်ချက် ကျည်ထိကာ ကျဆုံး။",
      "age": "47",
      "folder": "tun maung",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u htun maung",
      "enDetails": ""
   },
   {
      "name": "စည်သူရှိန် (ခ) မြတ်သူရှိန်",
      "confirmed": "TRUE",
      "date": "4/3/2021",
      "city": "ရန်ကုန်",
      "details": "မြောက်ဥက္ကလာ ဌ  ရပ်ကွက် သစ္စာပန်းလမ်း နေထိုင်။ အဝိုင်းကြီးမှာ စစ်တပ်နဲ့ ရဲတပ်ဖွဲ့ အကြမ်းဖက်ဒဏ်ရာရသူများအား ကူညီကယ်ဆယ်ဝင်ဆွဲပေးရင်း ကျည်ထိမှန်။ မနက် ၁နာရီခန့်တွင် ကွယ်လွန်။ မတ်လ ၆ရက် နေ့တွင် ရေဝေးသုသာန်၌ မီးသင်္ဂြိုလ်ခဲ့ပြီး အရိုးပြာကို ဂူသွင်းခဲ့။ https://bit.ly/3qryI5G",
      "age": "18",
      "folder": "sithu shain",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg sithu shein @ mg myat thu shein",
      "enDetails": ""
   },
   {
      "name": "မင်းဦး",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "ရန်ကုန်",
      "details": "မြောက်ဥက္ကလာပ  (၂)ရပ်ကွက် မာဃ အပိုင်း(၃) နေထိုင်သူ။ မြောက်ဥက္ကလာ၊ ဘုန်းကြီးလမ်း မှတ်တိုင်အနီး ဆီးအိမ်ကျည်မှန်ကာကျဆုံး။ ဇနီးသည်ကျန်ရစ်။ မတ်လ ၇ရက်နေ့တွင် ဇာပနကျင်းပ။ https://bit.ly/2OuZa1l https://bit.ly/3sZFRw4",
      "age": "21",
      "folder": "min oo",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko min oo",
      "enDetails": ""
   },
   {
      "name": "ဇွဲထက်စိုး",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "ရန်ကုန်",
      "details": "မြောက်ဒဂုံ ၄၂ ရပ်ကွက် မေတ္တာချောင်းကူးတွင်နေထိုင်။ မြောက်ဥက္ကလာပအ၀ိုင်းတွင် ပစ်ခတ်ခံရ၍ ဆုံးပါး။ ဇနီးနှင့် သမီးတစ်ယောက် ကျန်ရစ်။",
      "age": "26",
      "folder": "zwe htet soe",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko zwe htet soe",
      "enDetails": ""
   },
   {
      "name": "ရာဇာမင်း",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "ရန်ကုန်",
      "details": "မြောက်ဥက္ကလာပ",
      "age": "33",
      "folder": "",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko yarzar min",
      "enDetails": ""
   },
   {
      "name": "ဖိုးချစ်",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "ရန်ကုန်",
      "details": "မြောက်ဥက္ကလာပတွင် ဦးခေါင်းကျည်ထိမှန်ပြီး ကျဆုံးသွား၊ ဖွဲပြာရောင်းတဲ့အလုပ်နဲ့ အသက်မွေး၊ ဇနီးနဲ့အတူ ၆ နှစ်အရွယ် သားလေးတစ်ဦးကျန်ရှိ bit.ly/3eicFfz",
      "age": "22",
      "folder": "phoe chit",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko phoe chit",
      "enDetails": ""
   },
   {
      "name": "အာကာမိုး",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "ရန်ကုန်",
      "details": "မြောက်ဥက္ကလာပ",
      "age": "25",
      "folder": "",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko arkar moe",
      "enDetails": ""
   },
   {
      "name": "ထက်အောင် (ခ) ကိုရေသန့်",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "ရန်ကုန်",
      "details": "မြောက်ဥက္ကလာတွင် ရေသန့်ပို့အလုပ်လုပ်။ ဇနီးသည်နှင့် လသားကလေးကျန်ရစ်။ မတ်လ ၇ရက်နေ့တွင် ဇာပနကျင်းပ။ bit.ly/3q79ARK https://bit.ly/3kWkNU4",
      "age": "19",
      "folder": "htet aung",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg htet aung @ ko yay thant",
      "enDetails": ""
   },
   {
      "name": "အောင်မြင့်မြတ်",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "စလင်း (မကွေး)",
      "details": "၂၀၁၈ ငါးဘာသာဂုဏ်ထူးရှင်။ မကွေးနည်းပညာတက္ကသိုလ် မြို့ပြအင်ဂျင်နီယာ ဒုတိယနှစ်။ ကျည်ခေါင်းထိ ဆေးရုံရောက်ပြီးဆုံးသွား။ bit.ly/3q79ARK https://tinyurl.com/3mmfz29v https://tinyurl.com/5hbyr5py",
      "age": "19",
      "folder": "aung myint myat",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg aung myint myat",
      "enDetails": ""
   },
   {
      "name": "‌ဝေယံ (ခ) ကိုကံချွန်",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မုံရွာ",
      "details": "ပြည်ထောင်စုလမ်း၊ ဘုရားနီဘုရားအနီး ဆန္ဒပြလူထုအား ရဲနှင့်စစ်တပ်မှ သေနတ်ဖြင့်ပစ်ခတ်ဖြိုခွင်ခံရ၍သေဆုံး။ မတ်လ ၅ရက်နေ့တွင် နာရေးကျင်းပ။ https://bit.ly/3qqNgCH ",
      "age": "25",
      "folder": "wai yan",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko wai yan @ ko kan chon",
      "enDetails": ""
   },
   {
      "name": "ချမ်းသာဆွေ (ခ) ကဗျာဆရာ ကိုကေဇ၀င်း",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မုံရွာ",
      "details": "ဆားလင်းကြီးမြို့နယ် လက်ပံတောင်းကျေးရွာ bit.ly/30l2lLC",
      "age": "39",
      "folder": "k za win",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko chan thar swe @ poet k za win",
      "enDetails": ""
   },
   {
      "name": "နိုင်၀င်း",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မုံရွာ",
      "details": "bit.ly/3c6JglH bit.ly/3v0y5DU",
      "age": "45",
      "folder": "naing win",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko naing win",
      "enDetails": ""
   },
   {
      "name": "ဇော်သိန်းအောင်",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မုံရွာ",
      "details": "ထန်းတောရပ်ကွက်သား။ Foodpanda (မုံရွာ) ပို့ဆောင်သူ ပါတနာအဖြစ် တာဝန်ထမ်းဆောင်နေသူ။ ဆန္ဒထုတ်ဖော်ပွဲတွင် ဒဏ်ရာရရှိသွားခဲ့သော အမျိုးသမီးတစ်ဦးအား ကယ်ဆယ်ရန်ကြိုစားစဉ် ဦးခေါင်းအား ကျည်မှန်ခဲ့။ bit.ly/30yx9Zz",
      "age": "21",
      "folder": "zaw thein aung",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko zaw thein aung",
      "enDetails": ""
   },
   {
      "name": "မိုးအောင်",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မုံရွာ",
      "details": "မြဝတီရပ်မှ ကျူရှင်ဆရာ၊ မုံရွာတက္ကသိုလ်မှ ဒဿနိက ဒုတိယနှစ် ကျောင်းသား။ ဘုရားနီဘုရားသပိတ် အကြမ်းဖက်ဖြိုခွင်းခံရမူ့တွင် ကျဆုံး bit.ly/3b9kcLJ",
      "age": "23",
      "folder": "moe aung",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko moe aung",
      "enDetails": ""
   },
   {
      "name": "မြင့်မြင့်ဇင် (ခ) ကဗျာဆရာ ကြည်လင်အေး",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မုံရွာ",
      "details": "အောင်ချမ်းသာရပ်မှ ဆရာမ၊ ရင်ဘတ်တည့်တည့် သေနတ်ထိမှန်။ bit.ly/3b9kcLJ bit.ly/3qcF9JR bit.ly/3sRfto5",
      "age": "36",
      "folder": "myint myint zin",
      "gender": "f",
      "honorific": "ဒေါ်",
      "enName": "daw myint myint zin @ poet kyi lin aye",
      "enDetails": ""
   },
   {
      "name": "မင်းခန့်ကျော် (ခ) ဖိုးသဲ",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မုံရွာ",
      "details": "နန္ဒဝန်ရပ်။ မတ်လ ၄ရက်တွင် မြို့မသုသာန်သို့ ပို့ဆောင်ဂူသွင်းသဂြိုလ်။ bit.ly/3b9kcLJ",
      "age": "17",
      "folder": "min khant kyaw",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg min khant kyaw @ phoe thal",
      "enDetails": ""
   },
   {
      "name": "ကျော့နန္ဒာအောင်",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မုံရွာ",
      "details": "မြဝတီရပ်နေ မုံရွာကွန်ပျူတာတက္ကသိုလ်ကျောင်းသူဟောင်း။ ပြည်​ထောင်စုလမ်း၊ ဘုရားအနီး ပစ်ခတ်ဖြိုခွင်ခံရ၍ ခေါင်းထိသေဆုံး။ ly/3b9kcLJ bit.ly/3rdofMp bit.ly/3qcF9JR",
      "age": "25",
      "folder": "kyawt nandar aung",
      "gender": "f",
      "honorific": "မ",
      "enName": "ma kyawt nandar aung",
      "enDetails": ""
   },
   {
      "name": "မျိုးနိုင်လင်း (ခ) ဖိုးလင်း",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မန္တလေး",
      "details": "ရင်ဘတ်သေနတ်ဒဏ်ရာ bit.ly/3sQ4tat",
      "age": "39",
      "folder": "myo naing lin",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u myo naing lin @ phoe lin",
      "enDetails": ""
   },
   {
      "name": "နေမျိုးအောင် (ခ) ကုလား",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မန္တလေး",
      "details": "ပြည်ကြီးတံခွန် ဘ၂ကွက်စိတ်",
      "age": "16",
      "folder": "nay myoe aung",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg nay myoe aung @ mg kalar",
      "enDetails": ""
   },
   {
      "name": "ကြယ်စင် (ခ) Angel (ခ) တိန့်ကျားရှီး",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မန္တလေး",
      "details": "၈၄လမ်းနှင့် ၃၀လမ်းတွင် အကြမ်းဖက်ဖြိုခွင်းမှုခံရကာ ဦးခေါင်းကျည်ဆံထိ ကျဆုံးခဲ့။ ယူနန်ဘုံကျောင်းမှ အေးရိပ်ငြိမ်သုသာန်သို့ (ကြာနီကန်) မတ်လ ၄ ရက်နေ့တွင် ပို့ဆောင်သဂြိုဟ်။ bit.ly/3sQ4tat bit.ly/382F84T bit.ly/386fqNf (v)bit.ly/306aC65",
      "age": "19",
      "folder": "angel",
      "gender": "f",
      "honorific": "မ",
      "enName": "ma kwal sin @ angel @ taint kyar shee",
      "enDetails": ""
   },
   {
      "name": "ထက်‌ဝေထူး",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မော်လမြိုင်",
      "details": "ဦးခေါင်းသေနတ်ထိ၊ မော်လမြိုင်တက္ကသိုလ်ကျောင်းသားတစ်ဦးဖြစ်ပြီး တက္ကသိုလ် Dance Club အဖွဲ့ဝင်၊ လူငယ်လှုပ်ရှားမှုများတွင် တက်ကြွစွာပါဝင်သူတစ်ဦးဖြစ် bit.ly/3rfgbuG",
      "age": "23",
      "folder": "htet wai htoo",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko htet wai htoo",
      "enDetails": ""
   },
   {
      "name": "ဇင်ကိုကိုဇော်",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "မြင်းခြံ",
      "details": "အမှတ် ၁၉ စွန်းလွန်းရပ်ကွက်။ ဦးခေါင်းထိမှန် bit.ly/3sOOMjx",
      "age": "22",
      "folder": "zin ko ko zaw",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko zin ko ko zaw",
      "enDetails": ""
   },
   {
      "name": "ဇင်မျိုးမောင်",
      "confirmed": "TRUE",
      "date": "3/3/2021",
      "city": "ကလေး",
      "details": "မတ်လ ၂ ရက်နေ့က ဆန္ဒပြပွဲမှာ အဆုတ်နဲ့ ပေါင်ကို သေနတ်ထိမှန်ပြီး မတ်လ ၃ ရက်နေ့မှာ သေဆုံး။ တက္ကသိုလ်ဝင်တန်းအောင် shorturl.at/uEOR8 bit.ly/387Ok8l bit.ly/2OiZkc2",
      "age": "18",
      "folder": "zin myo maung",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko zin myo aung",
      "enDetails": ""
   },
   {
      "name": "သီဟဇော် (ခ) နောင်နောင်",
      "confirmed": "TRUE",
      "date": "2/3/2021",
      "city": "တောင်တွင်းကြီး (စစ်ကိုင်း)",
      "details": "တောင်တွင်းကြီးမြို့နယ်၊ ဆတ်သွား၊ အမှတ် ၅ ရပ်ကွက်မှာ နေထိုင်။ ရန်ကုန်-ပြည်ကားလမ်းအတိုင်း တောင်တွင်းကြီးဘက်သို့ ပြန်လာတဲ့ စစ်ကားတွေကို တောစိမ်းကျေးရွာထိပ် ကားလမ်းဘေးမှာ ထိုင်နေတဲ့ လူငယ်တွေက “စစ်အာဏာရှင်အလိုမရှိ” လို့ ကြွေးကြော်။ စစ်ကားပေါ်မှ စစ်သားများဆင်းလာပြီး ကျွဲကျောင်းရင်း ဂိမ်းဆော့နေတဲ့ လူငယ် ၂ ဦးကို ထိုးကြိတ်။ ထွက်ပြေးတဲ့ လူငယ်ကို  သေနတ်နဲ့ ပစ်တဲ့အတွက် ကျည်ဆန်ထိမှန် သေဆုံးခဲ့။ https://tinyurl.com/ch8mn8xy",
      "age": "16",
      "folder": "thiha zaw",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg thiha zaw @ naung naung",
      "enDetails": ""
   },
   {
      "name": "မောင်မောင်ဦး",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "မန္တလေး",
      "details": "မန္တလေးတောင်ခြေရှိ ရွှေမန်းတောင်ဂေါက်ကွင်းတွင် ဂေါက်အိတ်ထမ်းအဖြစ် လုပ်ကိုင်သူ။ ၄၁လမ်း၊ ၆၄လမ်းနှင့် ၆၅လမ်းကြားတွင် ဆိုင်ကယ်စီးနေချိန် ဦးခေါင်းကျည်မှန်၍ ကွယ်လွန်။ မိခင်၊ ဇနီး၊ အသက်(၁၀)နှစ်အောက် သားတစ်ဦးနှင့် တစ်နှစ်အရွယ် သမီးတစ်ဦးကျန်ရစ်။ https://tinyurl.com/c4chn4np (v) https://tinyurl.com/245pv2s8",
      "age": "41",
      "folder": "maung maung oo",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u maung maung oo",
      "enDetails": ""
   },
   {
      "name": "ကျော်ထက်ခေါင်",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "မန္တလေး",
      "details": "ဆိုင်ကယ်ဝပ်ရှော့လုပ်ငန်း လုပ်ကိုင်သူ။ ၆၈ လမ်း၊ ၃၄လမ်းနှင့် ၃၅ လမ်းကြားတွင် ညာဘက်ရင်အုံ သေနတ်ထိမှန်ကာ ကွယ်လွန်ခဲ့။ ဇနီးနှင့် ၇နှစ်အရွယ်သားကျန်ရစ်။ မတ်လ(၃)ရက်တွင် မဟာအောင်မြေ ယာဉ်ရပ်စခန်းဝင်းမှ သုသာန်သို့ ပို့ဆောင်။ https://tinyurl.com/23n7kra",
      "age": "28",
      "folder": "kyaw htet khaung",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko kyaw htet khaung",
      "enDetails": ""
   },
   {
      "name": "ဒေစီ (ခ) အပု (ခ) ရမ္မာဇာန်ဘီ",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "မန္တလေး",
      "details": "၃၅ လမ်း၊ ၇၅ လမ်းနှင့် ၇၆ လမ်းဘေးမှာ လမ်းလျှောက်နေရင်း အရပ်ဝတ်နဲ့ လူတစ်ဦးက ခေါင်းကိုသေချာ ချိန်ရွယ်ပစ်ခတ်ခံရမှုကြောင့် ဦးခေါင်း ထိမှန်သေဆုံး။ ၆နှစ်အရွယ်သားငယ် ကျန်ရှိ။ shorturl.at/eBDST (သွေးထွက်)shorturl.at/xBEI7 shorturl.at/bclE5",
      "age": "32",
      "folder": "daw si",
      "gender": "f",
      "honorific": "ဒေါ်",
      "enName": "daw daisy @ ah pu",
      "enDetails": ""
   },
   {
      "name": "သန်းဝင်း (ခ) ဂျွန်မာခမ်",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ထားဝယ်",
      "details": "ထားဝယ်မြို့၊ စျေးတောင်ဘက်လမ်းနှင့် ဗိုလ်ချုပ်လမ်းထောင့်အနီးတွင် ဒဏ်ရာဖြင့် လဲကျနေစဉ် ရဲတပ်ဖွဲ့က ချီမသယ်ဆောင်သွားခဲ့ပြီး ထားဝယ်ရဲစခန်းအချုပ်တွင်သေဆုံး။ ဗိုက်ပွင့်ထွက်ဒဏ်ရာဖြင့် သေဆုံးခဲ့။ အလောင်းကို တပ်မတော် ဆေးရုံတွင် မတ်လ ၁ ရက်နေ့ နေ့လယ်ပိုင်းတွင် မိသားစုက သွားရောက်ထုတ်ယူခဲ့။ ကရပ်​ပြင်​မြောက်​ဘက် ဇော်ကလေးလမ်း နေသူ shorturl.at/ixAKT shorturl.at/fnuyJ shorturl.at/tDT25",
      "age": "36",
      "folder": "than win",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u than win @ john mar khan",
      "enDetails": ""
   },
   {
      "name": "လွင်လွင်ဦး (ခ) အော့ကီး",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ထားဝယ်",
      "details": "ထားဝယ်မြို့ပုံကျွန်း/ဆန်းချီ ရပ်ကွက်နေသူ ထားဝယ်ဆေးရုံတွင် ကွယ်လွန်။ ဥတ္တံတားကြီး လမ်းဆုံတွင် ရှေ့တန်းလိုင်းမှ သံပြားကာထားသော်လည်း ကျည်ဆံထိ bit.ly/2ZUWGvA shorturl.at/fnsM6 shorturl.at/csBD1 shorturl.at/axBCJ shorturl.at/uNOYZ",
      "age": "33",
      "folder": "lwin lwin oo",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u lwin lwin oo @ ought kee",
      "enDetails": ""
   },
   {
      "name": "ဗညားအောင်",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ထားဝယ်",
      "details": "လောင်းလုံးမြို့နယ် ကျောက်ဆည်ရွာနေသူ ထားဝယ်ဆေးရုံတွင် ကွယ်လွန် bit.ly/2ZUWGvA shorturl.at/lmqvM shorturl.at/cwKQ1 shorturl.at/lCHV9",
      "age": "39",
      "folder": "banyar aung",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u banyar aung",
      "enDetails": ""
   },
   {
      "name": "နော်ငို (ခ) ကိုဖေသန်း",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ထားဝယ်",
      "details": "ရေဖြူမြို့နယ် ပုဂေါဇွန်းရွာနေသူ။ ညာဖက်နံကြားအောက် ကျည်ဝင်၊ မယ်ဒီလန်းဆေးရုံတွင် ကွယ်လွန်။ bit.ly/3dUSGDs bit.ly/3uEAB2A bit.ly/2ZUWGvA shorturl.at/knBQS (သွေး)shorturl.at/dqzE1",
      "age": "38",
      "folder": "ngaw ngo",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u ngaw ngo @ ko phay than",
      "enDetails": ""
   },
   {
      "name": "နေမျိုးဦး (ခ) နေလင်းဦး",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ပခုက္ကူ",
      "details": "ပခုက္ကူမြို့ အမှတ် ၃ ရပ်ကွက်၊ ဂကွင်း ၃ လမ်းနေ၊ ထင်တန်းလမ်း မြောက်ဘက်သို့ ရဲနှင့်စစ်တပ် တက်လာ၍  ကားဘေး၌ ပုန်းနေစဥ် ရဲမှ ပစ်ခတ်၍ ဘယ်ဘက်ပေါင်ရင်ကျည်ဆံထိမှန်၊ ပုန်းနေတုန်း ဂုတ်ကဆွဲကာ ဗိုက်ကိုထပ်ပစ်သဖြင့် ကွယ်လွန်။ ဇနီးနှင့် ကလေးငယ် ၂ ဦး(၆နှစ်နှင့်၂နှစ်ခွဲ) ကျန်ရစ်ခဲ့။ shorturl.at/dvDS8 shorturl.at/msz56 shorturl.at/ekpAS bit.ly/3q3O3cw shorturl.at/gnGJY (v)shorturl.at/cfCEG (v)bit.ly/383SDBn",
      "age": "35",
      "folder": "nay myoe oo",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u nay myo lin @ nay lin oo",
      "enDetails": ""
   },
   {
      "name": "ဟိန်းထွဋ်အောင်",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ရန်ကုန်",
      "details": "သင်္ဃန်းကျွန်း ဘဝမြင့်မှတ်တိုင်နားတွင် ကိုယ်ဝန်ဆောင် ဇနီးသည်နဲ့အတူရှိနေစဉ် ကျည်ဆံထိမှန်ကွယ်လွန်။ လည်ပင်းကို သေနတ်ကျည်ဆံထုတ်ချင်းပေါက်ဝင်ရောက်။ အတူတူရှိနေခဲ့တဲ့ ဇနီးသည်ဟာ ကိုယ်ဝန် ၃ လဆောင်ထားသူဖြစ်။ bit.ly/2Mvm0Fd bit.ly/2MCOHjO bit.ly/3uDq2MV bit.ly/3ktpd4Q shorturl.at/uyzS7",
      "age": "23",
      "folder": "hein htut aung",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko hein htut aung",
      "enDetails": ""
   },
   {
      "name": "တင်နွဲ့ရီ",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ရန်ကုန်",
      "details": "ကြည့်မြင်တိုင် ရန်ကုန်တိုင်းပညာရေးမှူးရုံးရှေ့ ဖြိုခွင်းမှုတွင် မျက်ရည်ယိုဗုံး ရော်ဘာကျည်နဲ့ပစ်တာ heart attackရ။ အလယ်တန်းပြဆရာမ ထ(ခွဲ)လ ၁၀ လှိုင်သာယာ(အနောက်မြို့နယ်) bit.ly/3kuODPk bit.ly/3ktwl10 bit.ly/3rfJIER bit.ly/3b40EbI shorturl.at/owNRS (v)bit.ly/3bQirlM",
      "age": "59",
      "folder": "tin nwae yee",
      "gender": "f",
      "honorific": "ဒေါ်",
      "enName": "daw tin nwae yee",
      "enDetails": ""
   },
   {
      "name": "ညီညီအောင်ထက်နိုင် (ခ) ညီညီ",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ရန်ကုန်",
      "details": "ရန်ကုန်အနောက်ပိုင်းတက္ကသိုလ်မှာ မြန်မာစာဘာသာရပ် တက္ကသိုလ်ကျောင်းသား။ လှည်းတန်း ကမာရွတ်တွင် သေနတ်ဒဏ်ရာဖြင့် ဗိုက်ပေါက်သွားပြီးကွယ်လွန်။ WYU ကျောင်းသား bit.ly/2ZUusRH bit.ly/3ktTBMx bit.ly/3uEYMO6 (အိမ်ရှိဗီဒီယို)bit.ly/3dPhrku (v)bit.ly/3uJijx4 (v)shorturl.at/hivTV shorturl.at/inoxC (v)shorturl.at/blzH8 (v)bit.ly/3uMIAur",
      "age": "23",
      "folder": "nyi nyi aung htet naing",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko nyi nyi aung htet naing @ nyi nyi",
      "enDetails": ""
   },
   {
      "name": "ဇင်လင်းထက်",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ရန်ကုန်",
      "details": "လှည်းတန်း ကမာရွတ် ၆လမ်းထိပ်တွင် သစ်သားဒိုင်းကိုပင် ဖောက်လာသောသေနတ်ဒဏ်ရာဖြင့် မျက်လုံးပေါက်သွားပြီး လမ်းတွင်ကွယ်လွန်။ ကျိုက်ထိုသား bit.ly/2MCOHjO bit.ly/3b08Edy bit.ly/3uEveAa shorturl.at/dnJK0 shorturl.at/asFN5 (v)bit.ly/3r3Y6jg https://bit.ly/3sHgFds",
      "age": "20",
      "folder": "zin lin htet",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko zin lin htet",
      "enDetails": ""
   },
   {
      "name": "ဇင်မျိုးသူ (ခ) ရရှစ်ဘိုင်",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "မော်လမြိုင်",
      "details": "စျေးကြိုရပ်၊ ရတနာထွန်းပွဲရုံအနီး ညနေငါးခွဲလောက်တွင် လုံထိန်းတပ်ဖွဲ့ ပစ်ခတ်မှုကြောင့် ဦးခေါင်းထိမှန်၍ ကွယ်လွန် shorturl.at/mxKWZ bit.ly/3r46b7D (သွေးထွက်)shorturl.at/sDHX6 (v)bit.ly/3b2Ey9c (v)shorturl.at/gE026",
      "age": "21",
      "folder": "zin myoe thu",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko zin myo thu",
      "enDetails": ""
   },
   {
      "name": "စည်သူစိုး (ခ) ကိုစိုး",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ပဲခူး",
      "details": "ဇိုင်းဂနိုင်းမြောက်ပိုင်းတွင် နေထိုင်သူ။ ပဲခူးတံတားပေါ်မှာ သေနတ်ဒဏ်ရာရကျဆုံး။ မတ်လ ၂ ရက်တွင် ဆင်ဖြူကွင်းသုသာန်မှာ ဂူသွင်းသင်္ဂြိုလ်။  shorturl.at/ahqA1",
      "age": "16",
      "folder": "sithu soe",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg sithu soe @ ko soe",
      "enDetails": ""
   },
   {
      "name": "ကြည်လှိုင်မင်း (ခ) ခေါင်းကြီး",
      "confirmed": "TRUE",
      "date": "28/2/2021",
      "city": "ပဲခူး",
      "details": "မဇင်း ၁လမ်း အိုးလေးစုပိုင်တွင် နေထိုင်သူ။  ဒို့ဗမာအစည်းအရုံးအဖွဲ့ဝင် သခင်လှကြိုင်ရဲ့မြစ်။ ပဲခူးတံတားပေါ်မှာ ကျည်ဆံမှန်ပြီး ကျဆုံး။ မတ်လ ၂ ရက်တွင် ဆင်ဖြူကွင်းသုသာန်မှာ ဂူသွင်းသင်္ဂြိုလ်။ shorturl.at/kzJV4 shorturl.at/npST8 https://tinyurl.com/yp863s6u",
      "age": "18",
      "folder": "kyi hlaing min",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg kyi hlaing min @ gong kyi",
      "enDetails": ""
   },
   {
      "name": "ရာဇာအောင်",
      "confirmed": "TRUE",
      "date": "24/2/2021",
      "city": "မန္တလေး",
      "details": "ဖေဖော်ဝါရီ ၂၀ ရက်နေ့ မန္တလေးဆိပ်ကမ်းတွင် ပစ်ခတ်ဖမ်းဆီးမှုကြောင့် ဒူးခေါင်းတွင် ကျည်ဆံထိမှန် ဖမ်းဆီးခံရ။ စစ်ကြောရေးစခန်းတွင် ဆေးကုသပေးခြင်းမရှိဘဲ ပစ်ထားရာ ၄ ရက်မြောက်နေ့တွင် ဒဏ်ရာပြင်းထန်၍ ဆုံးပါး။ သေဆုံးသောအခါ Covid လူနာအမည်တပ်၍ မိသားစု လက်မှတ်မထိုးသည့်ကြားမှ ချက်ချင်းသဂြိုလ်သည်။ bit.ly/3qWVW4R bit.ly/3bzBAbw bit.ly/3bErdD8",
      "age": "26",
      "folder": "yar zar aung",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko yarzar aung",
      "enDetails": ""
   },
   {
      "name": "သက်နိုင်ဝင်း (ခ) ကိုမင်းမင်း",
      "confirmed": "TRUE",
      "date": "20/2/2021",
      "city": "မန္တလေး",
      "details": "ဗိုက်ထဲကျည်ဆံဝင်၊ အသည်းထိသွားကာ ကျဆုံး။ ဖေဖော်၀ါရီ ၂၃တွင် ကြာနီကန်သုသာန်သို့ ပို့ဆောင်သဂြိုလ်။ bit.ly/3qGOcE3 shorturl.at/duUXZ",
      "age": "37",
      "folder": "thet naing win",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u thet naing win @ min min",
      "enDetails": ""
   },
   {
      "name": "ဝေယံထွန်း",
      "confirmed": "TRUE",
      "date": "20/2/2021",
      "city": "မန္တလေး",
      "details": "ဒဏ်ရာရသူများကို လှည်းဖြင့်တွန်းတင်ကာ ကူညီပေးသူ။ ကျည်ဆံကြားထဲ ဒဏ်ရာရသူကို ပြန်သွားကယ်ရာမှ ဦးခေါင်းသေနတ်ထိမှန်။ သား မရတော့ဘူးဟု နောက်ဆုံးပြောသွား",
      "age": "16",
      "folder": "wai yan htun",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg wai yan htun",
      "enDetails": ""
   },
   {
      "name": "ကြည်စိုး",
      "confirmed": "TRUE",
      "date": "20/2/2021",
      "city": "မန္တလေး",
      "details": "အကြမ်းဖက်မှုများကို မှတ်တမ်းတင်ရင်း အရိုက်ခံရသော ဒဏ်ရာဖြင့် ကွယ်လွန် bit.ly/3bt1aie",
      "age": "48",
      "folder": "kyi soe",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u kyi soe",
      "enDetails": ""
   },
   {
      "name": "လှမျိုးအောင်",
      "confirmed": "TRUE",
      "date": "20/2/2021",
      "city": "ရန်ကုန်",
      "details": "အင်းစိန်မြို့သစ်စျေးရှေ့ မသမာသူက ကားနဲ့တိုက် bit.ly/3kwZ30Z",
      "age": "39",
      "folder": "hla myoe aung",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u hla myoe aung",
      "enDetails": ""
   },
   {
      "name": "တင်ထွဋ်ဟိန်း",
      "confirmed": "TRUE",
      "date": "20/2/2021",
      "city": "ရန်ကုန်",
      "details": "ရွှေပြည်သာ ညကင်းစောင့်စဥ် ဖြတ်သွားသောရဲကားမှ ခေါင်းကိုသေနတ်ဖြင့် သုံးချက်ပစ်",
      "age": "30",
      "folder": "tin htut hein",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u tin htut hein",
      "enDetails": ""
   },
   {
      "name": "ချမ်းမြေ့အောင်",
      "confirmed": "-",
      "date": "20/2/2021",
      "city": "ရန်ကုန်",
      "details": "တောင်ဥက္ကလာပမှာ မီးကွင်းပစ်တယ်ဆိုလို့ ခြံကျော်လိုက်ရာမှ ဓာတ်လိုက် bit.ly/3pPYMHu",
      "age": "-",
      "folder": "chan myae aung",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko chan myae aung",
      "enDetails": ""
   },
   {
      "name": "စုစုနိုင်",
      "confirmed": "-",
      "date": "20/2/2021",
      "city": "ဘားအံ",
      "details": "ဒုက္ခသည်စခန်းတွင် မီးကွင်းပစ်ခံရပြီး မီးလောင် shorturl.at/lmyC2",
      "age": "4",
      "folder": "su su naing",
      "gender": "f",
      "honorific": "မ",
      "enName": "ma su su naing",
      "enDetails": ""
   },
   {
      "name": "ကြည်ဖြူဦး",
      "confirmed": "-",
      "date": "20/2/2021",
      "city": "ဘားအံ",
      "details": "ဒုက္ခသည်စခန်းတွင် မီးကွင်းပစ်ခံရပြီး မီးလောင် shorturl.at/lmyC2",
      "age": "2",
      "folder": "kyi phyu oo",
      "gender": "f",
      "honorific": "မ",
      "enName": "ma kyi phyu oo",
      "enDetails": ""
   },
   {
      "name": "မျိုးမင်းထွန်း",
      "confirmed": "TRUE",
      "date": "22/2/2021",
      "city": "ပဲခူး",
      "details": "မီးရထားဝန်ထမ်း ဖြစ်ကာ ဆန္ဒပြပွဲအတွင်း မူးလဲကာ ကွယ်လွန်။ bit.ly/3pKzdHT",
      "age": "44",
      "folder": "",
      "gender": "m",
      "honorific": "ဦး",
      "enName": "u myoe min htun",
      "enDetails": ""
   },
   {
      "name": "မြသွဲ့သွဲ့ခိုင်",
      "confirmed": "TRUE",
      "date": "19/2/2021",
      "city": "နေပြည်တော်",
      "details": "ဖေဖော်၀ါရီလ ၉ရက်နေ့တွင် ဦးခေါင်းကျည်ဆံထိမှန်ပြီး သေဆုံးလုနီးပါး ဖြစ်နေခဲ့။ ထိုနေ့ညတွင် နေပြည်တော် ကုတင် ၁၀၀၀ ဆေးရုံ၌ ဦးနှောက်သေဆုံးသွားခဲ့။ အသက်ရှူစက်ဖြင့် အသက်ဆက်ခဲ့ပြီး မိသားစုဝင်များက နောက်ရက်များ၌ အသက်ရှူစက်ဖြုတ်ခဲ့ရန် သဘောတူခဲ့။ ဖေဖော်ဝါရီ ၁၉ ရက်နေ့တွင် ကွယ်လွန်။ shorturl.at/boqKO shorturl.at/hlowN (v)shorturl.at/wBDGT",
      "age": "19",
      "folder": "mya thwat thwat khaing",
      "gender": "f",
      "honorific": "မ",
      "enName": "ma mya thwae thwae khaing",
      "enDetails": ""
   },
   {
      "name": "နေနေဝင်းထက်",
      "confirmed": "TRUE",
      "date": "15/2/2021",
      "city": "မြိတ်",
      "details": "ညကင်းစောင့်ရာမှ ခေါင်းကို အရိုက်ခံရ shorturl.at/lmyC2",
      "age": "15",
      "folder": "nay nay win htet",
      "gender": "m",
      "honorific": "မောင်",
      "enName": "mg nay nay win htet",
      "enDetails": ""
   },
   {
      "name": "တူးအောင် (ခ) မာတူး",
      "confirmed": "",
      "date": "8/2/2021",
      "city": "မန္တလေး",
      "details": "https://bit.ly/38oPFaT",
      "age": "43",
      "folder": "too aung",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko too aung @ mar too",
      "enDetails": ""
   },
   {
      "name": "နပွား (ခ) ကိုကိုဦး",
      "confirmed": "TRUE",
      "date": "8/2/2021",
      "city": "မန္တလေး",
      "details": "ညတွင် ကားဖြင့်ဆင့်တိုက်ခံရ",
      "age": "32",
      "folder": "na pwar",
      "gender": "m",
      "honorific": "ကို",
      "enName": "ko na pwar @ ko ko oo",
      "enDetails": "Hit and run at night"
   }
]

export default data