export const cityMappings: any = {
    // TODO: yea encoding ordering issues, yolo for now
    "မြိုင် (မ‌ကွေး)": "Myaing (Magway)",
    "မြိုင် (မကွေး)": "Myaing (Magway)",
    "ထားဝယ်": "Dawei",
    "မန္တလေး": "Mandalay",
    "ပဲခူး": "Bago",
    "မြင်းခြံ": "Myingyan",
    "ရန်ကုန်": "Yangon",
    "မုံရွာ": "Monywa",
    "မြစ်ကြီးနား": "Myitkyina",
    "ဖျာပုံ": "Pyapon",
    "ထီးလင်း (မကွေး)": "Tilin (Magway)",
    "မူဆယ်": "Muse",
    "ပင်လောင်း (ရှမ်းပြည်)": "Pinlaung (Shan)",
    "စလင်း (မကွေး)": "Salin",
    "မော်လမြိုင်": "Mawlamyine",
    "ကလေး": "Kale",
    "တောင်တွင်းကြီး (စစ်ကိုင်း)": "Taungdwingyi (Sagaing)",
    "ပခုက္ကူ": "Pakokku",
    "ဘားအံ": "Hpa-an",
    "နေပြည်တော်": "Naypyitaw",
    "မြိတ်": "Myeik",
    "မကွေး": "Magway",
    "ပြည်": "Pyay",
    "ချောက်": "Chauk",
    "တွံတေး": "Twantay",
    "ဖားကန့်": "Hpakant",
    "ဖားကန့်": "Hpakant"
}
    